# Generated by Django 3.1.3 on 2020-11-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('origin_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='EventLocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('origin_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GatheringModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('origin_id', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatherings', to='mainapp.districtmodel', verbose_name='mahalla')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('origin_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(null=True, unique=True, verbose_name='ID пользователя')),
                ('name', models.CharField(max_length=64, verbose_name='Имя пользователя')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.districtmodel')),
                ('event_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.eventlocationmodel')),
                ('gathering', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.gatheringmodel')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.regionmodel')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('event_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register', to='mainapp.eventlocationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.userprofile')),
            ],
            options={
                'verbose_name': 'Регистр',
                'verbose_name_plural': 'Регистр',
            },
        ),
        migrations.AddField(
            model_name='eventlocationmodel',
            name='gatherings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_location', to='mainapp.gatheringmodel'),
        ),
        migrations.AddField(
            model_name='districtmodel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='mainapp.regionmodel', verbose_name='tuman'),
        ),
    ]
