# Generated by Django 3.1.3 on 2020-11-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlocationmodel',
            old_name='gatherings',
            new_name='gathering',
        ),
    ]
